!!container.BeanDefinition
name: TestA
type: usercreatesample.beans.TestA
---
!!container.BeanDefinition
name: TestB
type: usercreatesample.beans.TestB
---
!!container.BeanDefinition
name: TestC
type: usercreatesample.beans.TestC