!!container.BusinessLogicDefinition
interfaceClass: usercreatesample.businessLogic.BusinessLogic
name: bl1
type: usercreatesample.businessLogic.BusinessLogicTestA
---
!!container.BusinessLogicDefinition
interfaceClass: usercreatesample.businessLogic.BusinessLogic
name: bl2
type: usercreatesample.businessLogic.BusinessLogicTestB
---
!!container.BusinessLogicDefinition
interfaceClass: usercreatesample.businessLogic.BusinessLogic
name: bl3
type: usercreatesample.businessLogic.BusinessLogicTestC
---
!!container.BusinessLogicDefinition
interfaceClass: usercreatesample.businessLogic.BusinessLogic
name: bl4
type: usercreatesample.businessLogic.BusinessLogicTestD